# Generated by Django 4.2.2 on 2023-07-02 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adminstration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Libelle_admi_ar', models.CharField(blank=True, max_length=200, null=True)),
                ('Libelle_admi_fr', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Libelle_grade_ar', models.CharField(blank=True, max_length=200, null=True)),
                ('Libelle_grade_fr', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SousAdminstration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Libelle_sousadmi_ar', models.CharField(blank=True, max_length=200, null=True)),
                ('Libelle_sousadmi_fr', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
