# Generated by Django 4.2.2 on 2023-07-02 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='name_fr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='prenom_ar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='prenom_fr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
